services:
  - type: web
    name: python-service
    env: docker
    rootDir: python-service
    dockerfilePath: python-service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: analyticore-db
          property: connectionString
      - key: JAVA_SERVICE_URL
        value: https://java-service.onrender.com
    healthCheckPath: /health

  - type: web
    name: java-service
    env: docker
    rootDir: java-service
    dockerfilePath: java-service/Dockerfile
    healthCheckPath: /actuator/health

  - type: static
    name: frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://python-service.onrender.com/api/v1

databases:
  - name: analyticore-db
    databaseName: analyticore
    user: analyticore
